# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SEED
email: contact@seed.run
sales_email: sales@seed.run
description: > # this means to ignore newlines until "baseurl:"
  Deploy, manage, and monitor
  Serverless applications
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://seed.run" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/og-image.png

console_url: "https://console.seed.run"
signup: "/signup"
request_demo: "/request-demo"
upgrade: "/upgrade"

# GitHub
github_org: "https://github.com/seed-run"
github_repo: "https://github.com/seed-run/homepage"
github_repo_errors_path: "/tree/master/_docs/serverless-errors"
github_edit_prefix: "/edit/master/"

cli_npm: "https://www.npmjs.com/package/@seed-run/cli"

newsletter_signup_form: "https://emailoctopus.com/lists/14c85084-324e-11ea-be00-06b4694bee2a/forms/subscribe"
twitter: "https://twitter.com/SEED_run"
twitter_username: "SEED_run"
discord_invite: "https://sst.dev/discord"
slack_invite: "https://serverless-stack.com/slack"
linkedin: "https://www.linkedin.com/company/seed-run/"
jobs_url: "https://serverless-stack.com/careers.html"

google_analytics: "UA-3536629-12"

permalink: /blog/:title:output_ext

collections:
  docs:
    output: true
  legal:
    output: true

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
exclude:
  - Session.vim
  - Gemfile
  - Gemfile.lock

# Front Matter defaults
defaults:
  - scope:
      path: ""
    values:
      image: /assets/social-cards/default.png
  - scope:
      type: "posts"
    values:
      image: /assets/social-cards/blog.png
  - scope:
      path: ""
      type: "docs"
    values:
      image: /assets/social-cards/docs.png
